// รายชื่อร้านค้า (จากไฟล์ "รายละเอียดแต่ละร้านค้า.xlsx")
// แก้ไข/เพิ่มร้านได้โดยเพิ่มบรรทัดใน array นี้แล้ว commit ขึ้น GitHub
const SHOP_LIST = [
  "Classy Missy Shop 2 (Pakret)",
  "nanhitz",
  "ถนัดขาย By Porpla",
  "Gentlejunior",
  "คุณแพง",
  "i am joy (คลองสามวา)",
  "A Beauti Box",
  "KKdelight",
  "คุณอั้ม",
  "MEELA Shop",
  "จอยลี่ มีทุกสิ่ง",
  "generoom",
  "n@m aboutsweet (K.Nat)",
  "L&J",
  "stayup",
  "Irasshais",
  "Elfelaa shop",
  "อุ๊กอิ๊กพาเพลิน",
  "Pre-order Australia by cream",
  "ร้านคุณส้ม",
  "Rina Shop (คุณนก)",
  "Pre order by ks (K.Ning)",
  "Thannaree.Sin",
  "Meeya Shop",
  "PreWithPui",
  "Pre Order By Porpier",
  "Tk.spy",
  "ร้านคุณแจง",
  "ซื้อก่อนสวยก่อน",
  "Reeya Brand/Reeya Skincare",
  "บริษัท วชิ อินเตอร์เนชั่นแนล กรุ๊ป",
  "Daisy by Suu",
  "sachagoodshop",
  "DUO DOUBLE",
  "HAPPY PUNN",
];
